// The starter movement library, seeded on first launch.
//
// Each row is [id, name, primaryMuscle, equipment, secondaryMuscles, cue] where
// `secondaryMuscles` is a comma-separated list and `cue` is the one thing worth
// reading before you attempt the movement. Rows stay tuples rather than objects
// so a list this long is still scannable.
//
// The id is permanent. It was generated from the name once and is now plain
// data: a row can be renamed or reworded freely and every workout that ever
// referenced it still resolves. Never reuse an id for a different movement.
//
// Bump LIBRARY_VERSION whenever rows change. Installs compare it on launch and
// refresh their copy — new rows are added, wording is updated — without
// touching anything the user wrote (notes, archived flags, custom exercises).
export const LIBRARY_VERSION = 2;

export const EXERCISE_LIBRARY = [
  // --- Chest ---------------------------------------------------------------
  ['barbell-bench-press', 'Barbell Bench Press', 'chest', 'barbell', 'triceps,shoulders',
    'Lie flat, grip just outside shoulder width, and lower the bar to mid-chest with elbows tucked near 45 degrees. Keep your shoulder blades pinned back and your feet driving into the floor.'],
  ['incline-barbell-bench-press', 'Incline Barbell Bench Press', 'chest', 'barbell', 'shoulders,triceps',
    'Set the bench to 30 degrees, no steeper — past that the front delts take over. Lower to the upper chest, just below the collarbone.'],
  ['decline-barbell-bench-press', 'Decline Barbell Bench Press', 'chest', 'barbell', 'triceps',
    'A 15 to 30 degree decline shifts load to the lower chest and takes the shoulders out of it. Lower to the bottom of the pecs.'],
  ['close-grip-bench-press', 'Close-Grip Bench Press', 'chest', 'barbell', 'triceps,shoulders',
    'Hands about shoulder width — narrower wrecks the wrists without adding triceps. Keep elbows tucked tight to the ribs throughout.'],
  ['floor-press', 'Floor Press', 'chest', 'barbell', 'triceps',
    'Pressing from the floor stops the rep when your upper arms touch down, sparing the shoulders and overloading the lockout.'],
  ['dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', 'dumbbell', 'triceps,shoulders',
    'Dumbbells let the arms travel a longer path than a bar allows. Lower until you feel a stretch across the chest, then press without clanging them together.'],
  ['incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', 'dumbbell', 'shoulders,triceps',
    'Bench at 30 degrees. Start with the dumbbells at chest level and press slightly inward so they finish over your upper chest, not your face.'],
  ['decline-dumbbell-press', 'Decline Dumbbell Press', 'chest', 'dumbbell', 'triceps',
    'Hook your feet, set a slight decline, and press. Get someone to hand you the dumbbells rather than muscling them into position.'],
  ['dumbbell-fly', 'Dumbbell Fly', 'chest', 'dumbbell', '',
    'Soft, fixed elbow bend the whole way — this is a hug, not a press. Go light; the stretched position is where injuries happen.'],
  ['incline-dumbbell-fly', 'Incline Dumbbell Fly', 'chest', 'dumbbell', 'shoulders',
    'Same fixed-elbow arc on a 30 degree incline, biasing the upper chest. Stop when your upper arms reach torso level.'],
  ['dumbbell-pullover', 'Dumbbell Pullover', 'chest', 'dumbbell', 'back,triceps',
    'Lie across or along a bench, hold one dumbbell over your chest, and lower it behind your head with barely-bent arms. Stop where the stretch bites.'],
  ['machine-chest-press', 'Machine Chest Press', 'chest', 'machine', 'triceps,shoulders',
    'Set the seat so the handles sit at mid-chest height. The fixed path makes this a good place to push close to failure safely.'],
  ['incline-machine-press', 'Incline Machine Press', 'chest', 'machine', 'shoulders,triceps',
    'Upper-chest bias with none of the balance demand. Useful late in a session when stabilisers are already cooked.'],
  ['pec-deck', 'Pec Deck', 'chest', 'machine', '',
    'Keep your back flat against the pad and squeeze with the chest, not the hands. Pause for a beat where the pads meet.'],
  ['smith-machine-bench-press', 'Smith Machine Bench Press', 'chest', 'machine', 'triceps,shoulders',
    'A fixed bar path, so you can train to failure without a spotter. Set the bench so the bar lands on mid-chest.'],
  ['cable-fly', 'Cable Fly', 'chest', 'cable', '',
    'Cables keep tension on the chest at every point, unlike dumbbells. Step forward into a slight stagger and bring your hands together in front of your sternum.'],
  ['low-to-high-cable-fly', 'Low-to-High Cable Fly', 'chest', 'cable', 'shoulders',
    'Pulleys at the bottom, hands finishing at collarbone height. Biases the upper chest.'],
  ['high-to-low-cable-fly', 'High-to-Low Cable Fly', 'chest', 'cable', '',
    'Pulleys at the top, hands finishing at your hips. Biases the lower chest.'],
  ['cable-crossover', 'Cable Crossover', 'chest', 'cable', '',
    'Cross one hand past the other at the end of each rep for a harder squeeze. Alternate which hand goes on top.'],
  ['push-up', 'Push-Up', 'chest', 'bodyweight', 'triceps,core',
    'Hands slightly wider than shoulders, body in one line from heel to head. Elbows back at 45 degrees, not flared out sideways.'],
  ['incline-push-up', 'Incline Push-Up', 'chest', 'bodyweight', 'triceps',
    'Hands on a bench or bar. The higher the hands, the easier — the regression to use before dropping to your knees.'],
  ['decline-push-up', 'Decline Push-Up', 'chest', 'bodyweight', 'shoulders,triceps',
    'Feet elevated, which shifts load to the upper chest and shoulders. Do not let your hips sag.'],
  ['diamond-push-up', 'Diamond Push-Up', 'chest', 'bodyweight', 'triceps',
    'Hands together under your sternum forming a triangle. Far more triceps than a standard push-up.'],
  ['chest-dip', 'Chest Dip', 'chest', 'bodyweight', 'triceps,shoulders',
    'Lean the torso forward about 30 degrees and let the elbows drift slightly out — upright dips train triceps instead. Stop when your upper arms reach parallel.'],
  ['banded-push-up', 'Banded Push-Up', 'chest', 'band', 'triceps,core',
    'Band across the upper back, ends under your palms. Resistance rises as you extend, matching the strength curve.'],

  // --- Back ----------------------------------------------------------------
  ['deadlift', 'Deadlift', 'back', 'barbell', 'hamstrings,glutes,core',
    'Bar over mid-foot, shins nearly touching. Take the slack out before you pull, keep the bar dragging up your legs, and finish standing tall without leaning back.'],
  ['sumo-deadlift', 'Sumo Deadlift', 'back', 'barbell', 'quads,glutes,core',
    'Wide stance, hands inside the knees. Shorter range and more leg drive than conventional — often kinder on the lower back.'],
  ['trap-bar-deadlift', 'Trap Bar Deadlift', 'back', 'barbell', 'quads,glutes',
    'Handles at your sides put the load in line with your body, so the lower back works less and the quads work more. The easiest deadlift to learn.'],
  ['rack-pull', 'Rack Pull', 'back', 'barbell', 'glutes',
    'Deadlift from pins at or just below the knee. Overloads the top half and hammers the upper back and traps.'],
  ['barbell-row', 'Barbell Row', 'back', 'barbell', 'biceps,shoulders',
    'Hinge to roughly 45 degrees and hold it — the torso should not rise as you pull. Row to the lower ribs, not the chest.'],
  ['pendlay-row', 'Pendlay Row', 'back', 'barbell', 'biceps',
    'Torso parallel to the floor, bar resets on the ground between every rep. Each rep starts dead, so it builds pulling power from a standstill.'],
  ['yates-row', 'Yates Row', 'back', 'barbell', 'biceps',
    'Underhand grip, torso around 60 degrees upright. Lets you handle more weight and hits the lower lats.'],
  ['t-bar-row', 'T-Bar Row', 'back', 'barbell', 'biceps,shoulders',
    'Neutral grip and a supported chest pad if available. Pull the handles to your stomach and hold the squeeze for a beat.'],
  ['barbell-shrug', 'Barbell Shrug', 'back', 'barbell', '',
    'Straight up and down — rolling the shoulders adds nothing but wear. Pause at the top for a full second.'],
  ['dumbbell-row', 'Dumbbell Row', 'back', 'dumbbell', 'biceps',
    'One hand and one knee on the bench. Pull the dumbbell to your hip, not your shoulder, and resist the urge to twist your torso for extra reps.'],
  ['chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', 'back', 'dumbbell', 'biceps,shoulders',
    'Face down on an incline bench. Removing the lower back from the equation means the lats get the work you intended.'],
  ['dumbbell-shrug', 'Dumbbell Shrug', 'back', 'dumbbell', '',
    'Load at your sides rather than in front, so the traps work through a slightly longer range.'],
  ['lat-pulldown', 'Lat Pulldown', 'back', 'cable', 'biceps',
    'Grip a little wider than shoulders. Lead with the elbows down and back, pull to the collarbone, and stop the bar at your chin height — behind the neck is not worth the shoulder risk.'],
  ['close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'back', 'cable', 'biceps',
    'Narrow neutral grip, longer range of motion, more lower-lat involvement. Drive elbows down toward your back pockets.'],
  ['neutral-grip-lat-pulldown', 'Neutral-Grip Lat Pulldown', 'back', 'cable', 'biceps',
    'Palms facing each other. The most shoulder-friendly pulldown variation and usually the strongest.'],
  ['straight-arm-pulldown', 'Straight-Arm Pulldown', 'back', 'cable', 'core',
    'Arms nearly locked, push the bar down in an arc to your thighs. Isolates the lats without the biceps taking over.'],
  ['seated-cable-row', 'Seated Cable Row', 'back', 'cable', 'biceps,shoulders',
    'Sit tall with a slight forward lean at the stretch. Pull to your navel, hold, and let the weight draw your shoulder blades apart on the way out.'],
  ['single-arm-cable-row', 'Single-Arm Cable Row', 'back', 'cable', 'biceps,core',
    'One arm at a time lets you rotate slightly into the stretch and get a longer range than a bar allows.'],
  ['cable-face-pull', 'Cable Face Pull', 'back', 'cable', 'shoulders',
    'Rope at eye height. Pull toward your forehead and externally rotate so your knuckles finish pointing behind you. Go light and do plenty of reps.'],
  ['machine-row', 'Machine Row', 'back', 'machine', 'biceps',
    'Fixed path, so you can chase failure safely. Set the chest pad so your arms reach full extension at the front.'],
  ['chest-supported-machine-row', 'Chest-Supported Machine Row', 'back', 'machine', 'biceps,shoulders',
    'The pad takes the lower back out entirely. The best rowing option on a day you have already deadlifted.'],
  ['machine-pullover', 'Machine Pullover', 'back', 'machine', 'chest',
    'Pure lat isolation with no grip or bicep limitation — rare and worth using if your gym has one.'],
  ['hyperextension', 'Hyperextension', 'back', 'machine', 'hamstrings,glutes',
    'Round the upper back slightly and drive with the glutes to target them, or stay rigid to target the spinal erectors. Do not hyperextend at the top.'],
  ['pull-up', 'Pull-Up', 'back', 'bodyweight', 'biceps,core',
    'Overhand, slightly wider than shoulders. Start from a dead hang and pull until your chin clears the bar. Add weight once you can do twelve clean reps.'],
  ['chin-up', 'Chin-Up', 'back', 'bodyweight', 'biceps',
    'Underhand and shoulder width. More biceps than a pull-up, and most people are stronger at it.'],
  ['neutral-grip-pull-up', 'Neutral-Grip Pull-Up', 'back', 'bodyweight', 'biceps',
    'Palms facing each other. Easiest on the elbows and shoulders of the three grips.'],
  ['inverted-row', 'Inverted Row', 'back', 'bodyweight', 'biceps,core',
    'Bar at hip height, body straight, pull your chest to the bar. The horizontal counterpart to a push-up, and the best pull-up progression.'],
  ['band-pull-apart', 'Band Pull-Apart', 'back', 'band', 'shoulders',
    'Arms straight, pull the band apart until it touches your chest. Cheap insurance for shoulder health between pressing sets.'],

  // --- Shoulders -----------------------------------------------------------
  ['overhead-press', 'Overhead Press', 'shoulders', 'barbell', 'triceps,core',
    'Bar on the front delts, elbows slightly ahead. Move your head back to let the bar pass, then push your head through at the top so the bar finishes over your mid-foot.'],
  ['push-press', 'Push Press', 'shoulders', 'barbell', 'triceps,quads',
    'A short dip and leg drive gets you past the sticking point, so you can overload the top of the press.'],
  ['behind-the-neck-press', 'Behind-the-Neck Press', 'shoulders', 'barbell', 'triceps',
    'Only worth doing if you have the shoulder mobility for it — most people do not. Go light and stop at ear level.'],
  ['barbell-upright-row', 'Barbell Upright Row', 'shoulders', 'barbell', 'back',
    'Pull to chest height with a grip about shoulder width. A narrow grip pulled high is a classic impingement recipe.'],
  ['seated-dumbbell-press', 'Seated Dumbbell Press', 'shoulders', 'dumbbell', 'triceps',
    'Back against the pad, dumbbells starting at ear height. Press up and slightly in, stopping just short of lockout to keep tension on the delts.'],
  ['arnold-press', 'Arnold Press', 'shoulders', 'dumbbell', 'triceps',
    'Start palms facing you and rotate outward as you press. The rotation adds front-delt work at the bottom.'],
  ['dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', 'dumbbell', '',
    'Lead with the elbows, not the hands, and stop at shoulder height. Go lighter than feels right — swinging turns this into a trap exercise.'],
  ['leaning-lateral-raise', 'Leaning Lateral Raise', 'shoulders', 'dumbbell', '',
    'Hold an upright and lean away from it. Leaning puts the side delt under tension at the bottom, where a normal raise has none.'],
  ['dumbbell-front-raise', 'Dumbbell Front Raise', 'shoulders', 'dumbbell', '',
    'Rarely needed — pressing already hammers the front delts. Include only if the front delts are a specific weak point.'],
  ['bent-over-reverse-fly', 'Bent-Over Reverse Fly', 'shoulders', 'dumbbell', 'back',
    'Hinge forward, arms hanging, and raise out to the sides with a soft elbow. Rear delts respond to reps, not load.'],
  ['dumbbell-upright-row', 'Dumbbell Upright Row', 'shoulders', 'dumbbell', 'back',
    'Dumbbells allow a more natural path than a bar. Pull to chest height with elbows leading.'],
  ['machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', 'machine', 'triceps',
    'Set the seat so the handles start at ear level. Good for pushing to failure without a bar over your head.'],
  ['reverse-pec-deck', 'Reverse Pec Deck', 'shoulders', 'machine', 'back',
    'Chest on the pad, arms sweeping back. The most consistent rear-delt movement in most gyms.'],
  ['machine-lateral-raise', 'Machine Lateral Raise', 'shoulders', 'machine', '',
    'Pads on the outside of the upper arms so the load sits where it should. Removes the temptation to swing.'],
  ['cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', 'cable', '',
    'Pulley at the bottom, cable crossing in front of your body. Constant tension from the very first degree of movement.'],
  ['cable-front-raise', 'Cable Front Raise', 'shoulders', 'cable', '',
    'Low pulley, raise to eye level. Keeps tension through the top, unlike a dumbbell.'],
  ['cable-reverse-fly', 'Cable Reverse Fly', 'shoulders', 'cable', 'back',
    'Cables crossed at chest height, pull apart and back. Excellent rear-delt work with tension throughout.'],
  ['face-pull', 'Face Pull', 'shoulders', 'cable', 'back',
    'Rope at eye height, pull to your forehead, knuckles rotating back. Do these often — they offset all the pressing.'],
  ['pike-push-up', 'Pike Push-Up', 'shoulders', 'bodyweight', 'triceps',
    'Hips high, head travelling toward the floor between your hands. The best bodyweight route to overhead pressing strength.'],
  ['handstand-push-up', 'Handstand Push-Up', 'shoulders', 'bodyweight', 'triceps,core',
    'Against a wall, lowering until your head touches the floor. Build up with pike push-ups first.'],
  ['kettlebell-overhead-press', 'Kettlebell Overhead Press', 'shoulders', 'kettlebell', 'triceps,core',
    'The bell rests on the back of the forearm, which forces more shoulder stability than a dumbbell.'],
  ['band-lateral-raise', 'Band Lateral Raise', 'shoulders', 'band', '',
    'Resistance builds as you raise, matching the delt strength curve. A good travel or warm-up option.'],

  // --- Biceps --------------------------------------------------------------
  ['barbell-curl', 'Barbell Curl', 'biceps', 'barbell', '',
    'Elbows pinned at your sides and still. If your shoulders swing forward to finish the rep, the weight is too heavy.'],
  ['ez-bar-curl', 'EZ-Bar Curl', 'biceps', 'barbell', '',
    'The angled grip takes strain off the wrists. Slightly less biceps peak than a straight bar, considerably more comfort.'],
  ['barbell-preacher-curl', 'Barbell Preacher Curl', 'biceps', 'barbell', '',
    'The pad stops any cheating. Control the bottom — the stretched position under load is where a bicep tear happens.'],
  ['barbell-drag-curl', 'Barbell Drag Curl', 'biceps', 'barbell', '',
    'Drag the bar up along your torso, elbows travelling back. Keeps tension on the long head through the top.'],
  ['dumbbell-curl', 'Dumbbell Curl', 'biceps', 'dumbbell', '',
    'Supinate as you curl so your palm faces up at the top — that final twist is what the biceps do.'],
  ['alternating-dumbbell-curl', 'Alternating Dumbbell Curl', 'biceps', 'dumbbell', '',
    'One arm at a time gives each side a brief rest, so the last reps are usually cleaner than a both-arms set.'],
  ['hammer-curl', 'Hammer Curl', 'biceps', 'dumbbell', 'forearms',
    'Neutral grip throughout. Trains the brachialis underneath the biceps, which pushes the peak up as it grows.'],
  ['incline-dumbbell-curl', 'Incline Dumbbell Curl', 'biceps', 'dumbbell', '',
    'Bench at 45 to 60 degrees with arms hanging behind you. The stretched start makes this the hardest and most productive curl.'],
  ['concentration-curl', 'Concentration Curl', 'biceps', 'dumbbell', '',
    'Elbow braced against the inner thigh. Nothing but the biceps can move the weight.'],
  ['dumbbell-preacher-curl', 'Dumbbell Preacher Curl', 'biceps', 'dumbbell', '',
    'One arm at a time on the preacher pad, which lets you fix any strength imbalance between sides.'],
  ['zottman-curl', 'Zottman Curl', 'biceps', 'dumbbell', 'forearms',
    'Curl up palms-up, rotate at the top, lower palms-down. Biceps on the way up, forearms on the way down.'],
  ['cable-curl', 'Cable Curl', 'biceps', 'cable', '',
    'Constant tension with no dead spot at the top, unlike a barbell where the load lightens near lockout.'],
  ['cable-hammer-curl', 'Cable Hammer Curl', 'biceps', 'cable', 'forearms',
    'Rope attachment, neutral grip, thumbs pulling apart at the top.'],
  ['bayesian-cable-curl', 'Bayesian Cable Curl', 'biceps', 'cable', '',
    'Face away from a low pulley with the arm behind your body. The deepest stretch available to a curl, and worth the setup.'],
  ['machine-preacher-curl', 'Machine Preacher Curl', 'biceps', 'machine', '',
    'Fixed path with even resistance. Ideal for drop sets at the end of an arm session.'],
  ['band-curl', 'Band Curl', 'biceps', 'band', '',
    'Stand on the band and curl. Hardest at the top where the biceps are strongest.'],

  // --- Triceps -------------------------------------------------------------
  ['skull-crusher', 'Skull Crusher', 'triceps', 'barbell', '',
    'Lower to your forehead or just behind your head — behind is easier on the elbows and keeps tension on. Keep the upper arms still.'],
  ['ez-bar-overhead-extension', 'EZ-Bar Overhead Extension', 'triceps', 'barbell', '',
    'Overhead puts the long head of the triceps on stretch, which no pushdown does. This is the size builder.'],
  ['jm-press', 'JM Press', 'triceps', 'barbell', 'chest',
    'Half skull crusher, half close-grip press. Lower toward your chin with elbows forward, then press back.'],
  ['dumbbell-overhead-extension', 'Dumbbell Overhead Extension', 'triceps', 'dumbbell', '',
    'Two hands on one dumbbell, lowered behind the head. Keep the elbows pointing forward, not flaring out.'],
  ['single-arm-overhead-extension', 'Single-Arm Overhead Extension', 'triceps', 'dumbbell', '',
    'One arm at a time, free hand supporting the working elbow. Easy to control and easy on the joints.'],
  ['dumbbell-kickback', 'Dumbbell Kickback', 'triceps', 'dumbbell', '',
    'Upper arm parallel to the floor and locked there. Only the forearm moves. Squeeze hard at full extension.'],
  ['dumbbell-skull-crusher', 'Dumbbell Skull Crusher', 'triceps', 'dumbbell', '',
    'Neutral grip is friendlier to the elbows than a bar, and each arm works independently.'],
  ['triceps-pushdown', 'Triceps Pushdown', 'triceps', 'cable', '',
    'Elbows glued to your ribs. Lock out fully and let the weight stretch the triceps at the top of each rep.'],
  ['rope-pushdown', 'Rope Pushdown', 'triceps', 'cable', '',
    'Pull the rope ends apart as you extend. The extra rotation gives a harder contraction than a straight bar.'],
  ['overhead-cable-extension', 'Overhead Cable Extension', 'triceps', 'cable', '',
    'Face away from the pulley, rope behind your head. Combines the overhead stretch with constant cable tension.'],
  ['single-arm-cable-pushdown', 'Single-Arm Cable Pushdown', 'triceps', 'cable', '',
    'Underhand or neutral grip, one arm at a time. Good for evening out a side-to-side difference.'],
  ['cross-body-cable-extension', 'Cross-Body Cable Extension', 'triceps', 'cable', '',
    'Extend across your body rather than straight down, which changes the angle on the lateral head.'],
  ['machine-triceps-extension', 'Machine Triceps Extension', 'triceps', 'machine', '',
    'Fixed path, no stabilising. A safe place to take the last set past failure.'],
  ['assisted-dip-machine', 'Assisted Dip Machine', 'triceps', 'machine', 'chest,shoulders',
    'Counterweighted dips. Stay upright to bias triceps; lean forward to bias chest.'],
  ['triceps-dip', 'Triceps Dip', 'triceps', 'bodyweight', 'chest,shoulders',
    'Stay upright with elbows tracking straight back. Lower until your upper arms reach parallel and no further.'],
  ['bench-dip', 'Bench Dip', 'triceps', 'bodyweight', 'shoulders',
    'Hands on a bench behind you, feet out front. Easy to load with a plate on your lap, but hard on the shoulders — do not go deep.'],
  ['close-grip-push-up', 'Close-Grip Push-Up', 'triceps', 'bodyweight', 'chest',
    'Hands under your shoulders, elbows brushing your ribs on the way down.'],
  ['band-pushdown', 'Band Pushdown', 'triceps', 'band', '',
    'Anchor high and extend down. A good warm-up before heavy pressing.'],

  // --- Quads ---------------------------------------------------------------
  ['back-squat', 'Back Squat', 'quads', 'barbell', 'glutes,hamstrings,core',
    'Bar on the upper traps, feet shoulder width, toes slightly out. Sit down between your hips rather than folding forward, and break parallel if your mobility allows.'],
  ['front-squat', 'Front Squat', 'quads', 'barbell', 'core,glutes',
    'Bar on the front delts with elbows high. The upright torso puts far more on the quads and far less on the lower back.'],
  ['high-bar-squat', 'High-Bar Squat', 'quads', 'barbell', 'glutes,core',
    'Bar high on the traps and a vertical torso. More quad than a low-bar squat, and usually a deeper position.'],
  ['box-squat', 'Box Squat', 'quads', 'barbell', 'glutes,hamstrings',
    'Sit back to a box, pause, then drive up. Teaches depth consistency and removes the bounce out of the bottom.'],
  ['pause-squat', 'Pause Squat', 'quads', 'barbell', 'glutes,core',
    'Two seconds at the bottom with no bounce. Brutal, and the fastest fix for a weak hole in your squat.'],
  ['zercher-squat', 'Zercher Squat', 'quads', 'barbell', 'core,glutes',
    'Bar held in the crooks of the elbows. Awkward and uncomfortable, but forces an upright torso and hammers the core.'],
  ['barbell-lunge', 'Barbell Lunge', 'quads', 'barbell', 'glutes,hamstrings',
    'Step out far enough that your front shin stays near vertical. Push through the front heel to return.'],
  ['barbell-step-up', 'Barbell Step-Up', 'quads', 'barbell', 'glutes',
    'Box at roughly knee height. Do not push off the trailing foot — the working leg does all of it.'],
  ['goblet-squat', 'Goblet Squat', 'quads', 'dumbbell', 'glutes,core',
    'Dumbbell held at the chest. The counterbalance lets most people squat deeper than they can with a bar.'],
  ['dumbbell-bulgarian-split-squat', 'Dumbbell Bulgarian Split Squat', 'quads', 'dumbbell', 'glutes,hamstrings',
    'Rear foot on a bench, front foot far enough forward that the knee stays over the ankle. The single most effective leg exercise most people avoid.'],
  ['dumbbell-step-up', 'Dumbbell Step-Up', 'quads', 'dumbbell', 'glutes',
    'Control the way down as well as the way up — the lowering half is where the growth is.'],
  ['dumbbell-front-squat', 'Dumbbell Front Squat', 'quads', 'dumbbell', 'glutes,core',
    'Dumbbells resting on the shoulders. A good bridge to barbell front squats without the wrist mobility demand.'],
  ['leg-press', 'Leg Press', 'quads', 'machine', 'glutes,hamstrings',
    'Feet mid-platform, shoulder width. Lower until your hips start to curl off the pad and no further. Never lock the knees hard at the top.'],
  ['hack-squat', 'Hack Squat', 'quads', 'machine', 'glutes',
    'Back supported, feet slightly forward. Loads the quads heavily with no balance or lower-back cost.'],
  ['leg-extension', 'Leg Extension', 'quads', 'machine', '',
    'Align the machine axis with your knee. Pause at the top — the squeeze is the point, not the weight.'],
  ['smith-machine-squat', 'Smith Machine Squat', 'quads', 'machine', 'glutes',
    'Feet slightly forward of the bar. The fixed path lets you push closer to failure than a free squat.'],
  ['pendulum-squat', 'Pendulum Squat', 'quads', 'machine', 'glutes',
    'An arcing path that keeps tension on the quads through the whole range. Use it if your gym has one.'],
  ['belt-squat', 'Belt Squat', 'quads', 'machine', 'glutes',
    'Load hangs from the hips, so the spine is unloaded entirely. The answer on a day your lower back is fried.'],
  ['sissy-squat', 'Sissy Squat', 'quads', 'bodyweight', '',
    'Knees travel forward as you lean back, hips staying extended. Extreme quad stretch — build up slowly.'],
  ['bodyweight-squat', 'Bodyweight Squat', 'quads', 'bodyweight', 'glutes',
    'The movement pattern with no load. Use it to warm up or to groove depth before adding weight.'],
  ['wall-sit', 'Wall Sit', 'quads', 'bodyweight', '',
    'Back on the wall, thighs parallel, hold. Log the seconds in the reps field.'],
  ['kettlebell-goblet-squat', 'Kettlebell Goblet Squat', 'quads', 'kettlebell', 'glutes,core',
    'Bell held by the horns at chest height. The most forgiving loaded squat to learn with.'],

  // --- Hamstrings ----------------------------------------------------------
  ['romanian-deadlift', 'Romanian Deadlift', 'hamstrings', 'barbell', 'glutes,back',
    'Push your hips back with a soft knee bend, bar dragging down your thighs. Stop when the stretch reaches its limit, usually around mid-shin — not the floor.'],
  ['stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'hamstrings', 'barbell', 'glutes,back',
    'Straighter legs and a longer range than an RDL, starting from the floor each rep. Go lighter than you think.'],
  ['good-morning', 'Good Morning', 'hamstrings', 'barbell', 'glutes,back',
    'Bar on the back, hinge forward to roughly parallel. Start absurdly light — the leverage is far harder than it looks.'],
  ['deficit-deadlift', 'Deficit Deadlift', 'hamstrings', 'barbell', 'glutes,back,quads',
    'Standing on a 2 to 4 inch platform, adding range at the hardest part of the lift.'],
  ['dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', 'dumbbell', 'glutes',
    'Dumbbells let the weights pass beside your legs, so you can get slightly deeper than with a bar.'],
  ['single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'hamstrings', 'dumbbell', 'glutes,core',
    'One leg down, the other extending behind as a counterweight. Balance limits the load, which is fine — the stretch is the point.'],
  ['lying-leg-curl', 'Lying Leg Curl', 'hamstrings', 'machine', 'calves',
    'Hips flat on the pad. Curl fully and lower under control; do not let the weight snap back.'],
  ['seated-leg-curl', 'Seated Leg Curl', 'hamstrings', 'machine', '',
    'The hip flexion puts the hamstrings on stretch, which makes this measurably better for growth than the lying version.'],
  ['standing-leg-curl', 'Standing Leg Curl', 'hamstrings', 'machine', '',
    'One leg at a time. Useful for correcting an imbalance between sides.'],
  ['glute-ham-raise', 'Glute-Ham Raise', 'hamstrings', 'machine', 'glutes,back',
    'Lower under control and pull yourself back with the hamstrings. Add a band or your hands on a bench until you can do it unassisted.'],
  ['nordic-curl', 'Nordic Curl', 'hamstrings', 'bodyweight', '',
    'Anchor your ankles and lower as slowly as you can, catching yourself with your hands. The strongest eccentric hamstring exercise there is.'],
  ['cable-pull-through', 'Cable Pull-Through', 'hamstrings', 'cable', 'glutes',
    'Rope between your legs from a low pulley. Pure hip hinge with the load pulling you backward, which teaches the pattern well.'],
  ['kettlebell-romanian-deadlift', 'Kettlebell Romanian Deadlift', 'hamstrings', 'kettlebell', 'glutes',
    'Bell held in front, hips pushing back. Good for high reps and learning the hinge.'],
  ['band-leg-curl', 'Band Leg Curl', 'hamstrings', 'band', '',
    'Anchor the band low and curl the heel toward the glute. A travel option or a finisher.'],

  // --- Glutes --------------------------------------------------------------
  ['hip-thrust', 'Hip Thrust', 'glutes', 'barbell', 'hamstrings',
    'Shoulder blades on a bench, bar over the hips with a pad. Drive through the heels and squeeze hard at the top with your ribs down.'],
  ['glute-bridge', 'Glute Bridge', 'glutes', 'barbell', 'hamstrings',
    'Same as a hip thrust but from the floor, so a shorter range. Good when a bench is not available.'],
  ['sumo-squat', 'Sumo Squat', 'glutes', 'barbell', 'quads,hamstrings',
    'Wide stance with toes turned out, which brings in the adductors and glutes far more than a standard squat.'],
  ['walking-lunge', 'Walking Lunge', 'glutes', 'dumbbell', 'quads,hamstrings',
    'Long strides and an upright torso. The longer the step, the more glute and the less quad.'],
  ['reverse-lunge', 'Reverse Lunge', 'glutes', 'dumbbell', 'quads',
    'Stepping backward is easier on the knees than stepping forward and keeps more load on the front leg.'],
  ['curtsy-lunge', 'Curtsy Lunge', 'glutes', 'dumbbell', 'quads',
    'Step back and across behind the standing leg. Targets the gluteus medius on the side of the hip.'],
  ['dumbbell-hip-thrust', 'Dumbbell Hip Thrust', 'glutes', 'dumbbell', 'hamstrings',
    'A dumbbell across the hips. Less loadable than a bar but far quicker to set up.'],
  ['machine-hip-thrust', 'Machine Hip Thrust', 'glutes', 'machine', 'hamstrings',
    'All of the hip thrust with none of the setup. Use it if your gym has one.'],
  ['hip-abduction-machine', 'Hip Abduction Machine', 'glutes', 'machine', '',
    'Push the knees apart against the pads. Lean forward slightly to bias the upper glute.'],
  ['cable-kickback', 'Cable Kickback', 'glutes', 'cable', 'hamstrings',
    'Ankle strap on a low pulley. Extend the hip back without arching your lower back to fake extra range.'],
  ['cable-hip-abduction', 'Cable Hip Abduction', 'glutes', 'cable', '',
    'Ankle strap, leg sweeping out to the side. Constant tension on the gluteus medius.'],
  ['single-leg-glute-bridge', 'Single-Leg Glute Bridge', 'glutes', 'bodyweight', 'hamstrings',
    'One foot planted, the other knee hugged in. Harder than it looks and needs no equipment.'],
  ['frog-pump', 'Frog Pump', 'glutes', 'bodyweight', '',
    'Soles of the feet together, knees out, hips pulsing up. Silly-looking and unreasonably effective for high reps.'],
  ['banded-hip-abduction', 'Banded Hip Abduction', 'glutes', 'band', '',
    'Band above the knees, pushing out. The standard warm-up before squats and hip thrusts.'],
  ['banded-glute-bridge', 'Banded Glute Bridge', 'glutes', 'band', 'hamstrings',
    'Band above the knees adds abduction to the bridge, which recruits more of the glute.'],
  ['kettlebell-swing', 'Kettlebell Swing', 'glutes', 'kettlebell', 'hamstrings,back,core',
    'A hip snap, not a squat and not a front raise. The bell floats to chest height on its own — your arms only steer it.'],

  // --- Calves --------------------------------------------------------------
  ['standing-calf-raise', 'Standing Calf Raise', 'calves', 'machine', '',
    'Knees straight, which targets the gastrocnemius. Full stretch at the bottom, one-second squeeze at the top, no bouncing.'],
  ['seated-calf-raise', 'Seated Calf Raise', 'calves', 'machine', '',
    'The bent knee shifts work to the soleus underneath. Both variations are needed for complete calves.'],
  ['leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', 'machine', '',
    'Balls of the feet on the bottom edge of the platform. Keep the safeties engaged.'],
  ['smith-machine-calf-raise', 'Smith Machine Calf Raise', 'calves', 'machine', '',
    'Stand on a plate for extra range. The fixed bar means no balance demand at heavy loads.'],
  ['barbell-calf-raise', 'Barbell Calf Raise', 'calves', 'barbell', '',
    'Bar on the back, toes on a plate. Simple, and works anywhere with a rack.'],
  ['dumbbell-calf-raise', 'Dumbbell Calf Raise', 'calves', 'dumbbell', '',
    'One dumbbell, one leg at a time, free hand on a wall for balance.'],
  ['single-leg-calf-raise', 'Single-Leg Calf Raise', 'calves', 'bodyweight', '',
    'Bodyweight on one leg gives most people plenty of resistance. Pause at the bottom of each rep.'],
  ['donkey-calf-raise', 'Donkey Calf Raise', 'calves', 'bodyweight', '',
    'Bent at the hips with the load on your lower back. The hip flexion gives the gastrocnemius a longer stretch.'],

  // --- Core ----------------------------------------------------------------
  ['plank', 'Plank', 'core', 'bodyweight', 'shoulders',
    'Elbows under shoulders, a straight line head to heel, glutes squeezed. Log the seconds in the reps field.'],
  ['side-plank', 'Side Plank', 'core', 'bodyweight', 'shoulders',
    'Trains the obliques and the lateral hip. Stack the feet and push the bottom hip up, not out.'],
  ['hanging-leg-raise', 'Hanging Leg Raise', 'core', 'bodyweight', '',
    'Curl the pelvis up rather than just lifting the legs — that is the difference between abs and hip flexors doing the work.'],
  ['hanging-knee-raise', 'Hanging Knee Raise', 'core', 'bodyweight', '',
    'The regression to use until you can control a straight-leg raise without swinging.'],
  ['captains-chair-leg-raise', 'Captain’s Chair Leg Raise', 'core', 'machine', '',
    'Back supported on the pads, so no swinging is possible and the abs do all the work.'],
  ['crunch', 'Crunch', 'core', 'bodyweight', '',
    'Short range by design — the shoulder blades barely leave the floor. Add weight once twenty reps is easy.'],
  ['bicycle-crunch', 'Bicycle Crunch', 'core', 'bodyweight', '',
    'Slow and deliberate, opposite elbow toward opposite knee. Speed defeats the purpose entirely.'],
  ['sit-up', 'Sit-Up', 'core', 'bodyweight', '',
    'Full range with the feet anchored. More hip flexor involvement than a crunch, which is fine.'],
  ['v-up', 'V-Up', 'core', 'bodyweight', '',
    'Legs and torso rising together to meet over your hips. Needs both strength and hamstring flexibility.'],
  ['dead-bug', 'Dead Bug', 'core', 'bodyweight', '',
    'Lower back pressed to the floor while opposite arm and leg extend. Anti-extension work that carries over to squats and deadlifts.'],
  ['bird-dog', 'Bird Dog', 'core', 'bodyweight', 'glutes,back',
    'Opposite arm and leg extending from all fours without the hips rotating. Slow beats many.'],
  ['mountain-climber', 'Mountain Climber', 'core', 'bodyweight', 'shoulders',
    'Push-up position, knees driving in alternately. Half core, half conditioning.'],
  ['hollow-body-hold', 'Hollow Body Hold', 'core', 'bodyweight', '',
    'Lower back flat, arms and legs off the floor. The gymnastics staple, and far harder than a plank.'],
  ['ab-wheel-rollout', 'Ab Wheel Rollout', 'core', 'other', 'shoulders,back',
    'Roll out only as far as you can without your lower back arching. Start from your knees.'],
  ['cable-crunch', 'Cable Crunch', 'core', 'cable', '',
    'Kneel facing the stack, rope by your head, and crunch with the abs — the hips stay still. The easiest core exercise to load progressively.'],
  ['cable-woodchop', 'Cable Woodchop', 'core', 'cable', 'shoulders',
    'Rotate from high to low across your body, pivoting the back foot. Trains rotation, which nothing else here does.'],
  ['pallof-press', 'Pallof Press', 'core', 'cable', 'shoulders',
    'Stand side-on and press the handle straight out, resisting the pull to rotate. Anti-rotation, and deceptively hard.'],
  ['machine-crunch', 'Machine Crunch', 'core', 'machine', '',
    'Loadable, fixed path, easy to progress. The most practical way to actually grow the abs.'],
  ['russian-twist', 'Russian Twist', 'core', 'dumbbell', '',
    'Feet up, rotating a weight side to side. Move from the ribcage, not the arms.'],
  ['weighted-plank', 'Weighted Plank', 'core', 'other', 'shoulders',
    'A plate on the upper back turns the plank back into a strength exercise once you can hold two minutes.'],
  ['farmers-carry', 'Farmer’s Carry', 'core', 'dumbbell', 'back,forearms',
    'Heavy weights at your sides, walking tall. Grip, core and traps all at once. Log the seconds or the distance in the reps field.'],
  ['suitcase-carry', 'Suitcase Carry', 'core', 'kettlebell', 'back',
    'Weight in one hand only, refusing to lean. One of the best oblique exercises there is.'],

  // --- Full body -----------------------------------------------------------
  ['power-clean', 'Power Clean', 'fullBody', 'barbell', 'back,quads,shoulders',
    'Explode from the floor and catch the bar on the front delts in a quarter squat. Technique before load, always.'],
  ['hang-clean', 'Hang Clean', 'fullBody', 'barbell', 'back,quads,shoulders',
    'Starting from the hang removes the floor pull, so it is easier to learn than a full clean.'],
  ['clean-and-jerk', 'Clean and Jerk', 'fullBody', 'barbell', 'shoulders,quads,back',
    'The full lift: floor to overhead in two movements. Worth coaching in person rather than from a description.'],
  ['snatch', 'Snatch', 'fullBody', 'barbell', 'shoulders,back,quads',
    'Floor to overhead in one pull. The most technical lift in the gym — get coaching.'],
  ['thruster', 'Thruster', 'fullBody', 'barbell', 'quads,shoulders,triceps',
    'Front squat straight into an overhead press. Brutal conditioning as much as strength work.'],
  ['barbell-complex', 'Barbell Complex', 'fullBody', 'barbell', 'back,quads,shoulders',
    'Several movements back to back without setting the bar down. Pick a weight limited by your weakest link.'],
  ['dumbbell-thruster', 'Dumbbell Thruster', 'fullBody', 'dumbbell', 'quads,shoulders',
    'Squat to overhead press with dumbbells. Easier on the wrists and shoulders than the barbell version.'],
  ['dumbbell-snatch', 'Dumbbell Snatch', 'fullBody', 'dumbbell', 'shoulders,back,glutes',
    'One dumbbell from between the feet to overhead in one movement. Far more forgiving than the barbell snatch.'],
  ['devils-press', 'Devil’s Press', 'fullBody', 'dumbbell', 'chest,shoulders,glutes',
    'A burpee followed by a two-dumbbell snatch. Extremely taxing; keep the reps low.'],
  ['kettlebell-clean-and-press', 'Kettlebell Clean and Press', 'fullBody', 'kettlebell', 'shoulders,back,glutes',
    'Clean to the rack position, then press. Let the bell roll around the wrist rather than flipping onto it.'],
  ['turkish-get-up', 'Turkish Get-Up', 'fullBody', 'kettlebell', 'shoulders,core',
    'Floor to standing with a bell locked out overhead. Slow, technical, and unmatched for shoulder stability.'],
  ['kettlebell-snatch', 'Kettlebell Snatch', 'fullBody', 'kettlebell', 'shoulders,back,glutes',
    'A swing that finishes overhead. Punch through at the top so the bell lands softly on the forearm.'],
  ['burpee', 'Burpee', 'fullBody', 'bodyweight', 'chest,quads',
    'Down to the floor, chest touching, then a jump. Pace yourself — the first ten always feel easy.'],
  ['bear-crawl', 'Bear Crawl', 'fullBody', 'bodyweight', 'core,shoulders',
    'Knees an inch off the floor, opposite hand and foot moving together. Log the seconds or distance in the reps field.'],

  // --- Cardio & conditioning -----------------------------------------------
  ['rowing-machine', 'Rowing Machine', 'cardio', 'machine', 'back,quads',
    'Legs, then back, then arms on the drive; reverse it on the recovery. Log minutes in the reps field.'],
  ['treadmill-run', 'Treadmill Run', 'cardio', 'machine', 'quads,calves',
    'Log minutes in the reps field and pace or incline in the weight field, whichever you are tracking.'],
  ['incline-treadmill-walk', 'Incline Treadmill Walk', 'cardio', 'machine', 'glutes,calves',
    'Ten to fifteen percent incline at a walking pace. Meaningful work with almost no recovery cost — the best cardio alongside lifting.'],
  ['stationary-bike', 'Stationary Bike', 'cardio', 'machine', 'quads',
    'Low impact and easy to recover from. Log minutes in the reps field.'],
  ['assault-bike', 'Assault Bike', 'cardio', 'machine', 'quads,back,shoulders',
    'Arms and legs together, resistance scaling with your effort. Miserable, and very effective.'],
  ['stair-climber', 'Stair Climber', 'cardio', 'machine', 'glutes,quads,calves',
    'Do not lean on the handles — it removes most of the work. Log minutes in the reps field.'],
  ['elliptical', 'Elliptical', 'cardio', 'machine', 'quads,glutes',
    'Zero impact. Useful when the joints need a break from running.'],
  ['skierg', 'SkiErg', 'cardio', 'machine', 'back,core,triceps',
    'Hinge at the hips and drive down with the whole torso, not just the arms.'],
  ['jump-rope', 'Jump Rope', 'cardio', 'other', 'calves',
    'Small jumps, wrists doing the turning. Log minutes or skips in the reps field.'],
  ['sled-push', 'Sled Push', 'cardio', 'other', 'quads,glutes,calves',
    'All concentric, so it builds conditioning with almost no soreness afterward.'],
  ['sled-drag', 'Sled Drag', 'cardio', 'other', 'hamstrings,glutes,back',
    'Walking backward loads the quads; forward loads the hamstrings and glutes.'],
  ['box-jump', 'Box Jump', 'cardio', 'bodyweight', 'quads,glutes,calves',
    'Step down between reps rather than jumping down — the landing is where achilles injuries happen.'],
];

/** Push / Pull / Legs plus an upper/lower split, seeded alongside the library. */
export const STARTER_ROUTINES = [
  ['Push Day', [
    ['Barbell Bench Press', 4, 6],
    ['Overhead Press', 3, 8],
    ['Incline Dumbbell Press', 3, 10],
    ['Dumbbell Lateral Raise', 3, 15],
    ['Rope Pushdown', 3, 12],
  ]],
  ['Pull Day', [
    ['Deadlift', 3, 5],
    ['Pull-Up', 4, 8],
    ['Barbell Row', 3, 8],
    ['Face Pull', 3, 15],
    ['Barbell Curl', 3, 10],
  ]],
  ['Leg Day', [
    ['Back Squat', 4, 6],
    ['Romanian Deadlift', 3, 8],
    ['Leg Press', 3, 12],
    ['Seated Leg Curl', 3, 12],
    ['Standing Calf Raise', 4, 15],
  ]],
  ['Upper Body', [
    ['Barbell Bench Press', 4, 6],
    ['Barbell Row', 4, 6],
    ['Seated Dumbbell Press', 3, 10],
    ['Lat Pulldown', 3, 10],
    ['Hammer Curl', 3, 12],
    ['Rope Pushdown', 3, 12],
  ]],
  ['Lower Body', [
    ['Back Squat', 4, 6],
    ['Hip Thrust', 3, 10],
    ['Romanian Deadlift', 3, 8],
    ['Leg Extension', 3, 15],
    ['Seated Calf Raise', 4, 15],
  ]],
];
