// The starter movement library, seeded on first launch.
// Rows are [name, muscleGroup, equipment]. Kept as terse tuples so the list can
// stay long without the file becoming unreadable.

export const EXERCISE_LIBRARY = [
  // --- Chest ---------------------------------------------------------------
  ['Barbell Bench Press', 'chest', 'barbell'],
  ['Incline Barbell Bench Press', 'chest', 'barbell'],
  ['Decline Barbell Bench Press', 'chest', 'barbell'],
  ['Close-Grip Bench Press', 'chest', 'barbell'],
  ['Floor Press', 'chest', 'barbell'],
  ['Dumbbell Bench Press', 'chest', 'dumbbell'],
  ['Incline Dumbbell Press', 'chest', 'dumbbell'],
  ['Decline Dumbbell Press', 'chest', 'dumbbell'],
  ['Dumbbell Fly', 'chest', 'dumbbell'],
  ['Incline Dumbbell Fly', 'chest', 'dumbbell'],
  ['Dumbbell Pullover', 'chest', 'dumbbell'],
  ['Machine Chest Press', 'chest', 'machine'],
  ['Incline Machine Press', 'chest', 'machine'],
  ['Pec Deck', 'chest', 'machine'],
  ['Smith Machine Bench Press', 'chest', 'machine'],
  ['Cable Fly', 'chest', 'cable'],
  ['Low-to-High Cable Fly', 'chest', 'cable'],
  ['High-to-Low Cable Fly', 'chest', 'cable'],
  ['Cable Crossover', 'chest', 'cable'],
  ['Push-Up', 'chest', 'bodyweight'],
  ['Incline Push-Up', 'chest', 'bodyweight'],
  ['Decline Push-Up', 'chest', 'bodyweight'],
  ['Diamond Push-Up', 'chest', 'bodyweight'],
  ['Chest Dip', 'chest', 'bodyweight'],
  ['Banded Push-Up', 'chest', 'band'],

  // --- Back ----------------------------------------------------------------
  ['Deadlift', 'back', 'barbell'],
  ['Sumo Deadlift', 'back', 'barbell'],
  ['Trap Bar Deadlift', 'back', 'barbell'],
  ['Rack Pull', 'back', 'barbell'],
  ['Barbell Row', 'back', 'barbell'],
  ['Pendlay Row', 'back', 'barbell'],
  ['Yates Row', 'back', 'barbell'],
  ['T-Bar Row', 'back', 'barbell'],
  ['Barbell Shrug', 'back', 'barbell'],
  ['Dumbbell Row', 'back', 'dumbbell'],
  ['Chest-Supported Dumbbell Row', 'back', 'dumbbell'],
  ['Dumbbell Shrug', 'back', 'dumbbell'],
  ['Lat Pulldown', 'back', 'cable'],
  ['Close-Grip Lat Pulldown', 'back', 'cable'],
  ['Neutral-Grip Lat Pulldown', 'back', 'cable'],
  ['Straight-Arm Pulldown', 'back', 'cable'],
  ['Seated Cable Row', 'back', 'cable'],
  ['Single-Arm Cable Row', 'back', 'cable'],
  ['Cable Face Pull', 'back', 'cable'],
  ['Machine Row', 'back', 'machine'],
  ['Chest-Supported Machine Row', 'back', 'machine'],
  ['Machine Pullover', 'back', 'machine'],
  ['Hyperextension', 'back', 'machine'],
  ['Pull-Up', 'back', 'bodyweight'],
  ['Chin-Up', 'back', 'bodyweight'],
  ['Neutral-Grip Pull-Up', 'back', 'bodyweight'],
  ['Inverted Row', 'back', 'bodyweight'],
  ['Band Pull-Apart', 'back', 'band'],

  // --- Shoulders -----------------------------------------------------------
  ['Overhead Press', 'shoulders', 'barbell'],
  ['Push Press', 'shoulders', 'barbell'],
  ['Behind-the-Neck Press', 'shoulders', 'barbell'],
  ['Barbell Upright Row', 'shoulders', 'barbell'],
  ['Seated Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Arnold Press', 'shoulders', 'dumbbell'],
  ['Dumbbell Lateral Raise', 'shoulders', 'dumbbell'],
  ['Leaning Lateral Raise', 'shoulders', 'dumbbell'],
  ['Dumbbell Front Raise', 'shoulders', 'dumbbell'],
  ['Bent-Over Reverse Fly', 'shoulders', 'dumbbell'],
  ['Dumbbell Upright Row', 'shoulders', 'dumbbell'],
  ['Machine Shoulder Press', 'shoulders', 'machine'],
  ['Reverse Pec Deck', 'shoulders', 'machine'],
  ['Machine Lateral Raise', 'shoulders', 'machine'],
  ['Cable Lateral Raise', 'shoulders', 'cable'],
  ['Cable Front Raise', 'shoulders', 'cable'],
  ['Cable Reverse Fly', 'shoulders', 'cable'],
  ['Face Pull', 'shoulders', 'cable'],
  ['Pike Push-Up', 'shoulders', 'bodyweight'],
  ['Handstand Push-Up', 'shoulders', 'bodyweight'],
  ['Kettlebell Overhead Press', 'shoulders', 'kettlebell'],
  ['Band Lateral Raise', 'shoulders', 'band'],

  // --- Biceps --------------------------------------------------------------
  ['Barbell Curl', 'biceps', 'barbell'],
  ['EZ-Bar Curl', 'biceps', 'barbell'],
  ['Barbell Preacher Curl', 'biceps', 'barbell'],
  ['Barbell Drag Curl', 'biceps', 'barbell'],
  ['Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Alternating Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Hammer Curl', 'biceps', 'dumbbell'],
  ['Incline Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Concentration Curl', 'biceps', 'dumbbell'],
  ['Dumbbell Preacher Curl', 'biceps', 'dumbbell'],
  ['Zottman Curl', 'biceps', 'dumbbell'],
  ['Cable Curl', 'biceps', 'cable'],
  ['Cable Hammer Curl', 'biceps', 'cable'],
  ['Bayesian Cable Curl', 'biceps', 'cable'],
  ['Machine Preacher Curl', 'biceps', 'machine'],
  ['Band Curl', 'biceps', 'band'],

  // --- Triceps -------------------------------------------------------------
  ['Skull Crusher', 'triceps', 'barbell'],
  ['EZ-Bar Overhead Extension', 'triceps', 'barbell'],
  ['JM Press', 'triceps', 'barbell'],
  ['Dumbbell Overhead Extension', 'triceps', 'dumbbell'],
  ['Single-Arm Overhead Extension', 'triceps', 'dumbbell'],
  ['Dumbbell Kickback', 'triceps', 'dumbbell'],
  ['Dumbbell Skull Crusher', 'triceps', 'dumbbell'],
  ['Triceps Pushdown', 'triceps', 'cable'],
  ['Rope Pushdown', 'triceps', 'cable'],
  ['Overhead Cable Extension', 'triceps', 'cable'],
  ['Single-Arm Cable Pushdown', 'triceps', 'cable'],
  ['Cross-Body Cable Extension', 'triceps', 'cable'],
  ['Machine Triceps Extension', 'triceps', 'machine'],
  ['Assisted Dip Machine', 'triceps', 'machine'],
  ['Triceps Dip', 'triceps', 'bodyweight'],
  ['Bench Dip', 'triceps', 'bodyweight'],
  ['Close-Grip Push-Up', 'triceps', 'bodyweight'],
  ['Band Pushdown', 'triceps', 'band'],

  // --- Quads ---------------------------------------------------------------
  ['Back Squat', 'quads', 'barbell'],
  ['Front Squat', 'quads', 'barbell'],
  ['High-Bar Squat', 'quads', 'barbell'],
  ['Box Squat', 'quads', 'barbell'],
  ['Pause Squat', 'quads', 'barbell'],
  ['Zercher Squat', 'quads', 'barbell'],
  ['Barbell Lunge', 'quads', 'barbell'],
  ['Barbell Step-Up', 'quads', 'barbell'],
  ['Goblet Squat', 'quads', 'dumbbell'],
  ['Dumbbell Bulgarian Split Squat', 'quads', 'dumbbell'],
  ['Dumbbell Step-Up', 'quads', 'dumbbell'],
  ['Dumbbell Front Squat', 'quads', 'dumbbell'],
  ['Leg Press', 'quads', 'machine'],
  ['Hack Squat', 'quads', 'machine'],
  ['Leg Extension', 'quads', 'machine'],
  ['Smith Machine Squat', 'quads', 'machine'],
  ['Pendulum Squat', 'quads', 'machine'],
  ['Belt Squat', 'quads', 'machine'],
  ['Sissy Squat', 'quads', 'bodyweight'],
  ['Bodyweight Squat', 'quads', 'bodyweight'],
  ['Wall Sit', 'quads', 'bodyweight'],
  ['Kettlebell Goblet Squat', 'quads', 'kettlebell'],

  // --- Hamstrings ----------------------------------------------------------
  ['Romanian Deadlift', 'hamstrings', 'barbell'],
  ['Stiff-Leg Deadlift', 'hamstrings', 'barbell'],
  ['Good Morning', 'hamstrings', 'barbell'],
  ['Deficit Deadlift', 'hamstrings', 'barbell'],
  ['Dumbbell Romanian Deadlift', 'hamstrings', 'dumbbell'],
  ['Single-Leg Romanian Deadlift', 'hamstrings', 'dumbbell'],
  ['Lying Leg Curl', 'hamstrings', 'machine'],
  ['Seated Leg Curl', 'hamstrings', 'machine'],
  ['Standing Leg Curl', 'hamstrings', 'machine'],
  ['Glute-Ham Raise', 'hamstrings', 'machine'],
  ['Nordic Curl', 'hamstrings', 'bodyweight'],
  ['Cable Pull-Through', 'hamstrings', 'cable'],
  ['Kettlebell Romanian Deadlift', 'hamstrings', 'kettlebell'],
  ['Band Leg Curl', 'hamstrings', 'band'],

  // --- Glutes --------------------------------------------------------------
  ['Hip Thrust', 'glutes', 'barbell'],
  ['Glute Bridge', 'glutes', 'barbell'],
  ['Sumo Squat', 'glutes', 'barbell'],
  ['Walking Lunge', 'glutes', 'dumbbell'],
  ['Reverse Lunge', 'glutes', 'dumbbell'],
  ['Curtsy Lunge', 'glutes', 'dumbbell'],
  ['Dumbbell Hip Thrust', 'glutes', 'dumbbell'],
  ['Machine Hip Thrust', 'glutes', 'machine'],
  ['Hip Abduction Machine', 'glutes', 'machine'],
  ['Cable Kickback', 'glutes', 'cable'],
  ['Cable Hip Abduction', 'glutes', 'cable'],
  ['Single-Leg Glute Bridge', 'glutes', 'bodyweight'],
  ['Frog Pump', 'glutes', 'bodyweight'],
  ['Banded Hip Abduction', 'glutes', 'band'],
  ['Banded Glute Bridge', 'glutes', 'band'],
  ['Kettlebell Swing', 'glutes', 'kettlebell'],

  // --- Calves --------------------------------------------------------------
  ['Standing Calf Raise', 'calves', 'machine'],
  ['Seated Calf Raise', 'calves', 'machine'],
  ['Leg Press Calf Raise', 'calves', 'machine'],
  ['Smith Machine Calf Raise', 'calves', 'machine'],
  ['Barbell Calf Raise', 'calves', 'barbell'],
  ['Dumbbell Calf Raise', 'calves', 'dumbbell'],
  ['Single-Leg Calf Raise', 'calves', 'bodyweight'],
  ['Donkey Calf Raise', 'calves', 'bodyweight'],

  // --- Core ----------------------------------------------------------------
  ['Plank', 'core', 'bodyweight'],
  ['Side Plank', 'core', 'bodyweight'],
  ['Hanging Leg Raise', 'core', 'bodyweight'],
  ['Hanging Knee Raise', 'core', 'bodyweight'],
  ['Captain’s Chair Leg Raise', 'core', 'machine'],
  ['Crunch', 'core', 'bodyweight'],
  ['Bicycle Crunch', 'core', 'bodyweight'],
  ['Sit-Up', 'core', 'bodyweight'],
  ['V-Up', 'core', 'bodyweight'],
  ['Dead Bug', 'core', 'bodyweight'],
  ['Bird Dog', 'core', 'bodyweight'],
  ['Mountain Climber', 'core', 'bodyweight'],
  ['Hollow Body Hold', 'core', 'bodyweight'],
  ['Ab Wheel Rollout', 'core', 'other'],
  ['Cable Crunch', 'core', 'cable'],
  ['Cable Woodchop', 'core', 'cable'],
  ['Pallof Press', 'core', 'cable'],
  ['Machine Crunch', 'core', 'machine'],
  ['Russian Twist', 'core', 'dumbbell'],
  ['Weighted Plank', 'core', 'other'],
  ['Farmer’s Carry', 'core', 'dumbbell'],
  ['Suitcase Carry', 'core', 'kettlebell'],

  // --- Full body -----------------------------------------------------------
  ['Power Clean', 'fullBody', 'barbell'],
  ['Hang Clean', 'fullBody', 'barbell'],
  ['Clean and Jerk', 'fullBody', 'barbell'],
  ['Snatch', 'fullBody', 'barbell'],
  ['Thruster', 'fullBody', 'barbell'],
  ['Barbell Complex', 'fullBody', 'barbell'],
  ['Dumbbell Thruster', 'fullBody', 'dumbbell'],
  ['Dumbbell Snatch', 'fullBody', 'dumbbell'],
  ['Devil’s Press', 'fullBody', 'dumbbell'],
  ['Kettlebell Clean and Press', 'fullBody', 'kettlebell'],
  ['Turkish Get-Up', 'fullBody', 'kettlebell'],
  ['Kettlebell Snatch', 'fullBody', 'kettlebell'],
  ['Burpee', 'fullBody', 'bodyweight'],
  ['Bear Crawl', 'fullBody', 'bodyweight'],

  // --- Cardio & conditioning -----------------------------------------------
  ['Rowing Machine', 'cardio', 'machine'],
  ['Treadmill Run', 'cardio', 'machine'],
  ['Incline Treadmill Walk', 'cardio', 'machine'],
  ['Stationary Bike', 'cardio', 'machine'],
  ['Assault Bike', 'cardio', 'machine'],
  ['Stair Climber', 'cardio', 'machine'],
  ['Elliptical', 'cardio', 'machine'],
  ['SkiErg', 'cardio', 'machine'],
  ['Jump Rope', 'cardio', 'other'],
  ['Sled Push', 'cardio', 'other'],
  ['Sled Drag', 'cardio', 'other'],
  ['Box Jump', 'cardio', 'bodyweight'],
];

/** Push / Pull / Legs, seeded alongside the library as a starting point. */
export const STARTER_ROUTINES = [
  ['Push Day', [
    ['Barbell Bench Press', 4, 6],
    ['Overhead Press', 3, 8],
    ['Incline Dumbbell Press', 3, 10],
    ['Dumbbell Lateral Raise', 3, 15],
    ['Rope Pushdown', 3, 12],
  ]],
  ['Pull Day', [
    ['Deadlift', 3, 5],
    ['Pull-Up', 4, 8],
    ['Barbell Row', 3, 8],
    ['Face Pull', 3, 15],
    ['Barbell Curl', 3, 10],
  ]],
  ['Leg Day', [
    ['Back Squat', 4, 6],
    ['Romanian Deadlift', 3, 8],
    ['Leg Press', 3, 12],
    ['Seated Leg Curl', 3, 12],
    ['Standing Calf Raise', 4, 15],
  ]],
  ['Upper Body', [
    ['Barbell Bench Press', 4, 6],
    ['Barbell Row', 4, 6],
    ['Seated Dumbbell Press', 3, 10],
    ['Lat Pulldown', 3, 10],
    ['Hammer Curl', 3, 12],
    ['Rope Pushdown', 3, 12],
  ]],
  ['Lower Body', [
    ['Back Squat', 4, 6],
    ['Hip Thrust', 3, 10],
    ['Romanian Deadlift', 3, 8],
    ['Leg Extension', 3, 15],
    ['Seated Calf Raise', 4, 15],
  ]],
];
